### ISSUE TITLE
제작자의 디자인 감각이 의심됨.

### ISSUE THREAD

**Issue by euidong** [huijjj/hui.gg#1]
<img width="1387" alt="스크린샷 2021-08-10 오후 12 30 57" src="https://user-images.githubusercontent.com/48043626/128804118-d16a1796-924c-42a2-8bf9-2b16877ad2ad.png">

검색 자동완성이 왼쪽으로 밀려서 지저분해요

**Comment by huijjj** [comment]
자동완성 끄셈
